### ISSUE TITLE
When clicking on the checkbox and filling up the form, you are losing the activated state of the sign up button

### ISSUE THREAD

**Issue by artnerdnet** [SydneySky1/Challenges#5]
https://github.com/SydneySky1/Challenges/blob/5d8aab4b7cf7cda9fceab3989b443b8faabc5c8a/form.js#L3

**Comment by SydneySky1** [comment]
Yes I believe this portion uses JS to make it more "magical" correct?  If that's the case, I've only just started learning JS right now, nothing about DOM or how to incorporate JS into HTML/CSS yet. Let me know anyway if this portion is the one where we need to add more JS?

**Comment by artnerdnet** [comment]
@SydneySky1 ok I understand! we can work on it later on
