### ISSUE TITLE
Too unspecific name for the class

### ISSUE THREAD

**Issue by artnerdnet** [SydneySky1/Challenges#7]
When naming classes, variables and functions, think if a developer who you don't know that is looking at your code would understand exactly what it does or what it modifies
https://github.com/SydneySky1/Challenges/blob/5d8aab4b7cf7cda9fceab3989b443b8faabc5c8a/app.css#L63

**Comment by SydneySky1** [comment]
After looking at it again, it made me laugh! I'll remember this one thanks for your input! :)
